apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: database
  namespace: victoriametrics
spec:
  retentionPeriod: "30d"
  removePvcAfterDelete: true
  storage:
    storageClassName: nfs-agate
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 1Gi
