apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-adapter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-adapter
    targetRevision: 5.3.0
    helm:
      values: |
        prometheus:
          url: http://prometheus-kube-prometheus-prometheus.prometheus.svc
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus-adapter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
