apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - applications/namespaces-ingress.yaml
  - applications/metallb.yaml
  - applications/metallb-config.yaml
  - applications/cert-manager.yaml
  - applications/ingress-nginx.yaml
  - applications/monitoring-lb.yaml
