apiVersion: v1
kind: Secret
metadata:
    name: plex-secrets
    namespace: media
stringData:
    token: ENC[AES256_GCM,data:X93ljmFidZphp+5JuQMvLEWm/+o=,iv:8xRvV02VyHHbgAXHAEupHH/W4Zn5qW0d0qdeRshV5nw=,tag:WoFX9HrUmE3hs9Za/TxddA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdXhZZXVoNE9Nd2c4a2tE
            cHh4NlhZNkdNcXhhaGVQRE9ReC9HQzJjNGw4CkhJRHpKL3ZsWDluaG42V1NPRUZ5
            a01INC92T1hvenZOZk5hY3d4a2wxMWsKLS0tIGNaYkRQekVyYy9DU002cncxQkFP
            dFZYZ0g5N2xCR3BVdUkxVXc5aDJ3cmcKTOjtelDoK9mRx8GGKGRA6RjVCieBJjNZ
            l1EBlApMc2z1KsT/cwD4xX2RVA/bSFVtfQjTUjI00T6Suxh4wuVl3g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1adrjn5x90yz0rkxfya8cwf0pl3x9syyukpfj2u4xsawaf6x40pxsnqc338
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T13:48:54Z"
    mac: ENC[AES256_GCM,data:lheSM7bTiYfIp/fzffo4XPMPE5iglLp/Ul8inG+GZK7E7c+MbWIF3l59Qxaoh+uBsrEks2GIG5SV2un2s8PX2F9aPiTG9QExyH529xf7dcGJl5AuK7C5Hc9pTFWUtkTLH8ch46PKzY1YQhlpmrsK7YUxPkcE4RRFM8EVhKza0+s=,iv:d8sX2ElHcS3NneheVErQMOlgwitJA53hXwfpowcWjaY=,tag:pSuA/QiJ/D83Ga+Av4d9Vg==,type:str]
    version: 3.13.3
