apiVersion: v1
kind: Secret
metadata:
    name: proton-wireguard
    namespace: media
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:vBKlZLVun1ZEAnVzs5LYSzoy+dvKywC6gWBpWQNwbU5XUALN9tNPiigcZtk=,iv:/5HdLa9Oxty92ID3G61+YXO91077TTTFCpzHiqnpPgg=,tag:Xx8DTqgACw3mjVmIjz+WuQ==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:ZpjZAmLBhxFQqgk=,iv:fjhO1q/LltihgxDT9HsvEv3p7gviuWofK7FDAZAovvg=,tag:/SiGVI/2Ewq6P2E2wyUFzw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYkFtZk5aVFJYNW1uYUl6
            RVRSWm5qQlRqenN4NnBTUityeTlldHZGaHpVCkR3dnRjYUVHb0hBaU80bmlzZjQz
            NElXbEpGUFF3VVNzOEZVc1QwTTJJYVkKLS0tIFBiWjMvTERuSVl4RWk5SWdGMG1r
            ZVZIOGw3TW5zK0xmSVM2M21Kck9FVGcKBU8rWnbKy58aZzLbFxeZb35mtEbI9cpw
            WMTAibqpkicTYhADyYUG983hmy8UPUnnSFAYa9SSrk90jgLSjA25yg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1adrjn5x90yz0rkxfya8cwf0pl3x9syyukpfj2u4xsawaf6x40pxsnqc338
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T23:04:42Z"
    mac: ENC[AES256_GCM,data:e+7NiGYrtJ6rV5HrF6TD8i1+hsO25i5u1EnORhb/Puv6DPf4sxP/vhQWK4FiTDp5r1jgg6XPUshJCKDie3GZ1m1BDD0MMyQ6NBiuzNHq4TvVEFqJjhCRf9g9R86P3wyJYaNhFk2EQMxDI3KIfDp257p4337DtyWoTucke8tZLVM=,iv:anD9am5JLMzCEBIWT/4sfPTCEraUPUoqUtH+HhPe0VI=,tag:NNt8R0PFLgH/AJZgONHvew==,type:str]
    version: 3.13.3
