apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-secrets
    namespace: media
stringData:
    api_key: ENC[AES256_GCM,data:DSdGZBqxnPchQkm1FJCX+Q2n8Lve593tNFIZ8EHS9xM=,iv:l6fR83f8w53yAgwEg5krX0NT6d5KWsaeL3QMHWiaBMY=,tag:MgT6KqXgh2sOTU8E2kyTjA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWUdPQlV4dmhmRGxyU3BJ
            UVQzV1ZFZGVoSW5PcFc2a0hReUpiR1VheFFFCklHYWRVaGRmV2g2MjE0SEdTUVZX
            bytUMzVua3JENzNYaUVkSzlTQW9ZajgKLS0tIGlrVjExVjFoVDhYSXY3T1hnd2FU
            OGJKSFBDUGVzamxZaWtnK3ZsREFNeTQKzJ6j96XvV2Bq1tl5IUFPyczE9md8493k
            3oLvwnfZlcH9adS9/jXm73P6vQvYVO1IB/e6dpqkYE2cOgHI6MTLnQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1adrjn5x90yz0rkxfya8cwf0pl3x9syyukpfj2u4xsawaf6x40pxsnqc338
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T15:07:13Z"
    mac: ENC[AES256_GCM,data:m9JWy2dGDkAs4q4M+lFCJcSGVH5ty4GyG/WqiiJ16lQHEC1vQMJNNQBgnzH0omfEjQVb+g/L0rAm8R8/HadMZ8jhVgMnoKV+uFR1Fhb1LMXHOVqWWuzb+sXmD78SNflquxnrYxrtVjYv4eHJKv0+Tv7yAzYqd0uz8BCvDbxx0q0=,iv:cdJbFherBKSKeh+rrDr5wYQoH6s7rmfxudC1yoeDBY4=,tag:TB3emTirLiD7g1ROklchXQ==,type:str]
    version: 3.13.3
