apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-secrets
    namespace: media
stringData:
    api_key: ENC[AES256_GCM,data:x6ADP5+gVvvJa6eKwlTt8PK/Gx6NFDNrs4sn5xvl/88=,iv:/5L0LP0S9aItkeIEHBihEM0ITEc+8gRTuJ3KRaqK6ac=,tag:5vsUDodrC0pHsVqMK0hGvQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWUdPQlV4dmhmRGxyU3BJ
            UVQzV1ZFZGVoSW5PcFc2a0hReUpiR1VheFFFCklHYWRVaGRmV2g2MjE0SEdTUVZX
            bytUMzVua3JENzNYaUVkSzlTQW9ZajgKLS0tIGlrVjExVjFoVDhYSXY3T1hnd2FU
            OGJKSFBDUGVzamxZaWtnK3ZsREFNeTQKzJ6j96XvV2Bq1tl5IUFPyczE9md8493k
            3oLvwnfZlcH9adS9/jXm73P6vQvYVO1IB/e6dpqkYE2cOgHI6MTLnQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1adrjn5x90yz0rkxfya8cwf0pl3x9syyukpfj2u4xsawaf6x40pxsnqc338
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T21:51:24Z"
    mac: ENC[AES256_GCM,data:c5GIZDtkgQnYpUZV4LOPhjXKv0xjQ0XhjQEy+QRkWtmUzpO/e3Vks6UAuNDU+f4xciO0BUFPEIRgXm9zSN7ryEsdKJm+KIqUBUF4cr8heBptndQ7TzbfEJnFoQqxZkvPcQ2SWhD7D4II2mveH4dWDdUWSzlAvPJSnfacBmh0/Z8=,iv:VUA/F++L4+RReDAfBa/f0RTZQg6YTifZ+zT+SbxVkfw=,tag:WyUPa+3UP+owunTXwT5kXA==,type:str]
    version: 3.13.3
