apiVersion: v1
kind: Secret
metadata:
    name: radarr-secrets
    namespace: media
stringData:
    api_key: ENC[AES256_GCM,data:v7EupAUldJmp55bkdb0usSmj08BnpphDHuPhdtwpRD8=,iv:TU1/mTuNg5oV5EqktLzH2N462D2bSmanSjZssoMfgrU=,tag:4x3+4zWA1KqG0n4HYsnYyQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvc05TeHc4QldINnBxUklN
            SzdIemtHWjJQNWd5a3NyaFRrNmY1Y2ZYWUJzClpPajY3MHcxVW9HU2hVdVhJTmxu
            ZmNhOTM4Y1VVY0JTNnNGT0RvdS9FWjAKLS0tIGhPK2FRc2lTZlUydnNGNkk4Z1ZZ
            bzhsN1E3cGk3SVFmSUhaKzhQRlo1Q2cKH1yhpr4rQVbRX8oQrLpr+lm+Ypz59Ijp
            iuE9nJ76qrfmj2iHVQevbhiD2+pZ5LkgDAENah61Qyc2OciInMGk/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1adrjn5x90yz0rkxfya8cwf0pl3x9syyukpfj2u4xsawaf6x40pxsnqc338
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T23:22:16Z"
    mac: ENC[AES256_GCM,data:puT9aV09WJvgRFh01n3OmTC8P+9+zIRLFg/69a+FbViZyjMxLo2sTrY2DEAWxs3FYeyHnS6PAL5iM8GcCqhDWoNz/Yvrli3CnqjcLp2Dh8DJFINAzcxN3eZfjCeB9I4QA9sm75LOo8KPtbYzF3Y+e4gViU6CZTWyblcRiMvxKU0=,iv:d1CXjVkvjd6Cj748fYw73tbSAVCHnBBTS35Kj5L9GPc=,tag:lCY8h/tbZEKodpjAQKXpQQ==,type:str]
    version: 3.13.3
