apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd-secrets
    namespace: media
stringData:
    api_key: ENC[AES256_GCM,data:T1tEydo5e+UaOzlsQd6VTzfnKNEr3vA8h5IzAt+4mwo=,iv:PAcsMnP9QAD81ixjcwwp7S1MbYuS48ikv8iZ4dLB6Qs=,tag:W6LZ5UQsgoPUqRifR1ZQxg==,type:str]
    usenet_username: ENC[AES256_GCM,data:bdvWab/0ncEG,iv:sD7pfG6NGbaPwTN7BFA2Yy1Igcgdx7hcdb6c0jcQ1sQ=,tag:TBthSTIC/Bk/VFdiOUcGLA==,type:str]
    usenet_password: ENC[AES256_GCM,data:tRoAOubG/SR5gWrL,iv:ywqBdpgGsiWttPJNsU6kulWKgXw8ZIH5eUjhXrUXJKc=,tag:5VMnVWuqzEN4dBiZAIR6lA==,type:str]
    webui_username: ENC[AES256_GCM,data:sCyDXBw=,iv:B/rnpkvK222hZ8/v7Du8xCDcWj0eqdUyktnc8qHnuy0=,tag:HJr+STyTkTKwr5SchMRffw==,type:str]
    webui_password: ENC[AES256_GCM,data:QBgl1fm17KyvnctoMBijtCs0xNW9hA==,iv:4KM/sqpUd25+89u8/FRyKbOIt3GeAjg+eP8P945lug8=,tag:r4fMUjp7fAxosb8YFFM2oA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6U0pIUHVIR09hbys2akVE
            L1g4TjJxN3NkVEsxYzlHN1lsWlRqRjIyd0IwCitoL0dhbEZYRWprR29lTlRQTC9m
            YUR6UHhETDg1a3Iycm43TndmbDRrRlUKLS0tIEF1V0QyQ0dLSlBUL056bHRCZXcv
            cmlaNHFONG1vOFpSeTBzai9tRFVFRmsKhGSFNHF3sWRXAdyvqpuV9fB8dshBoNds
            IuHF2cOFk6cX0izm4Q5M6ccmlvanam12fOOTRfu3F2mu3XisekBQwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1adrjn5x90yz0rkxfya8cwf0pl3x9syyukpfj2u4xsawaf6x40pxsnqc338
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T21:21:20Z"
    mac: ENC[AES256_GCM,data:vcNMFl42vs7SJsuJWMUwrjzJ4Kl5F1XYpPlYhXMXqzZtoruLE/7Ex6rWhk0AyZwpFzS9iU2kVObDQAYPiylac2jcyaihQIg+d2D31Ogapg2bVFsDOeomdfAKc33lu9u8TmbJqFc7MtX15Oo6eMcFZ96sRb4E+nAQf21ls/+kaJI=,iv:JsP2Wp/nAR4zfQDxy2MQ4zW/Sx5FiIwRnI6IzEAM+fQ=,tag:OaGYlQWqNML0SUWC0EZihQ==,type:str]
    version: 3.13.3
