apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secrets
    namespace: media
stringData:
    api_key: ENC[AES256_GCM,data:9FAH7cullhYkNnoC3abC1Y4SlTTprY+kTVPfePXYj8M=,iv:eD3eVeXLR53buWGfweeKNMmzQ8YnE+mUsIv6/aWXBg8=,tag:ADggLf9qRNVmO9mxg5GJrg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVmNnZHRya1NnWmpaYTNy
            SjBZSElCUHluRFlPNnFMK2NxdUg2cXo4dVd3CnRXK051YnQ3UWh5ajVzUHVqUjgz
            RGFwaWhOd2FHb2QvQzVwNDVuSWNGeG8KLS0tIFBlQlgyQldHZmY2OVQxSGxpL1Y1
            cnU0REhkQVJ1Z1d3U2RybUpVYUd5K3cKsYMkssRSzBFfMBYukShR2AnetxWMPKZV
            F9BR5ZB7jkhexZKhVXRdYsWTbgrZ1rI4tw0742//M1I3VUnPVw+n+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1adrjn5x90yz0rkxfya8cwf0pl3x9syyukpfj2u4xsawaf6x40pxsnqc338
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T05:49:06Z"
    mac: ENC[AES256_GCM,data:Bto8UwBkgWKPE0jdOficLL6xb6FEmrtu/6Rj1DKsB7d01laxdmHkN7MXWvuiOLPlXLWtDD4/UVc7mCgbXsXHuDBmy0Wd2HwLg72zSXpKW/v8yr20mjrEB5+TFrHy35rsCbVYajtinJ174A4uDDKC0KwE/PxbqBkiMZ7jv58s1H8=,iv:3qmD53YK+soiJJopd2/fAtGu10X8S6l/y75altUs00g=,tag:Y3pKbIALP6DSzIltEJxRag==,type:str]
    version: 3.13.3
