apiVersion: v1
kind: Secret
metadata:
    name: tautulli-secrets
    namespace: media
stringData:
    api_key: ENC[AES256_GCM,data:4RGS4Q/xX5CBLnaxfgDL2iPXMqjf6XAZH9nj/KJ3P8M=,iv:54hkXzpvVO7iJDFNdciLUayeDetbQcwFq48yOWOHEz8=,tag:gUcA8yI9Wc3FryRtqelg+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNazR5VnhFa2VoK1lnT2Zn
            aGluVTlBcGo1d3VsRVJYVnczN0NCQ2xYazBFCnhQam14SnF2VEl3azk3Qm9MVFps
            TnI2Uy9uMVlES1FqWjd5dW8vMGhqRGMKLS0tIFpXM3FmQ0oybm1OY2pEVXIyMHdK
            U0hZM0dVWWduK1VZdlpydlY1NkhMakEKicMgY46iFHr60PXuvekkDfYx6kz5H2iW
            oJyWi9CEpiYzEf5dspo+XcXPPun0KGh4E0fuo8GHSaxQHdYdVh3Qbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1adrjn5x90yz0rkxfya8cwf0pl3x9syyukpfj2u4xsawaf6x40pxsnqc338
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T13:48:54Z"
    mac: ENC[AES256_GCM,data:dH/nXFTEGJTIZn5tk9zuIcXUfH7v72bRofsDnOd3+MpjwmlaUX0GuhpQ185SK8mwhVFShIrBRUNzaIO0/93BINHENsoK+SIKO3JKzpIdRFCVwkeiXgTZReMunqPXJ9JyYvcWBQ8gqSEsg6BwMfBIBHvkU53hgXs0RnK9boFHnjo=,iv:Bsk92WKpS4W16HZny/iedqUpjNtKAIU/Z1wfdqqNjPo=,tag:0s+TIN6hROQ06iwp4JGLzg==,type:str]
    version: 3.13.3
