apiVersion: v1
kind: Secret
metadata:
    name: webui-auth
    namespace: media
stringData:
    username: ENC[AES256_GCM,data:PTCgbk4=,iv:ey7hg/CSMG8sA8+cOMEuWcxPK+6N+c2m4oU+PooXUng=,tag:bNsPOHb1OStRXELuTNZtEg==,type:str]
    password: ENC[AES256_GCM,data:uE2IDSk5o37D74+Ny+Jdh4vP72J0GQ==,iv:W69tPcGhGcUbu/T8LU42UQVupJz5qGrUFO4WXOgO2B8=,tag:T+jCoGBU7WjF0EgRLk6qrQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYm5DZTRNeW5RcEZvTi95
            ZEhROGVXKzNPSXlmSHVsOTVXcXd2RTdrVGdJCnI2RSsrbGJ4Wm5wa2tNdVNERTdN
            cnZkSk9xam5hUjR4SE5SOTN4eG9WZjQKLS0tIG5zd24yWnZ1Z0ZPcWNIN05nYmNN
            TGNOYjVjRFU2VWVmTUZldXZQQlRQQW8KJuxkNvcn8AoQi/M7G1NvsKALLon1gX+u
            Rzmma58pAu+N29jsPeodY2sp41jLjf4lWqyOtxfuLQwA6Ox+/8csPg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1adrjn5x90yz0rkxfya8cwf0pl3x9syyukpfj2u4xsawaf6x40pxsnqc338
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T21:51:24Z"
    mac: ENC[AES256_GCM,data:SLIeH9NlpkpM52g+dCvKNkyNNYP0m0yyjnvGghJ6QR695UfsomR/dNaN9rZJ1Bmy1uqJhVywSnrssU+jcztVzlPrZdWKUGEzZJ/6RWUN1IcVfl5CLEJZ3Lrb9RrCBkMFnXkL54MjnaL+veUXjUQb3N21R7wPnkIXgCzytcPGeh4=,iv:fm/veI3B23dSIlOJ9FdyyIYvLUqJTcIuZcPdljnHh10=,tag:xIs91Zs675l6DWRQeiYbTg==,type:str]
    version: 3.13.3
