apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/alanlaird/gitops
    targetRevision: main
    path: projects/o11y/components/ingress/glue/namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
