apiVersion: v1
kind: Service
metadata:
  name: media-landing
  namespace: media
  annotations:
    metallb.io/loadBalancerIPs: "172.16.16.227"
spec:
  type: LoadBalancer
  selector: { app: media-landing }
  ports:
    - port: 80
      targetPort: 80
