apiVersion: v1
kind: Service
metadata:
  name: tubesync
  namespace: media
  annotations:
    metallb.io/loadBalancerIPs: "172.16.16.226"
spec:
  type: LoadBalancer
  selector: { app: tubesync }
  ports:
    - port: 4848
      targetPort: 4848
